### ISSUE TITLE
Webui is always getting desynced with stuck/buttons not loading at all requiring many refreshes to do anything

### ISSUE THREAD

**Issue by Reinbowsaur** [Engineer-of-Stuff/stable-diffusion-paperspace#10]
Wondering if anyone else is experiencing this on paperspace? Is it to do with this setup?
Maybe some limitation/on free gpus with network speed/rates? Generation speeds are fine, but when it comes to using the webui things turn south and lock up quick from the get go or just after a few generations.

**Comment by Cyberes** [comment]
Well I used to suggest ngrok but rumor has it that paperspace is locking accounts for that sort of thing. You'll have to host a tunnel proxy yourself -> https://github.com/anderspitman/awesome-tunneling
