### ISSUE TITLE
Please help, what is the problem?

### ISSUE THREAD

**Issue by a48475715** [Engineer-of-Stuff/stable-diffusion-paperspace#101]
Thank you very much for sharing. I have been using Stable Diffusion through Gradient for a long time. Recently, when I tried to create a new notebook, it kept failing with some errors. I think it should be related to xFormers. I don't know how to solve it. There are many errors at this step. Please help me to see what the problem is.
![image](https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/assets/13452117/ce4be52a-06c2-4923-bf42-5c2846a7594e)

**Comment by a48475715** [comment]
I can start Stable Diffusion but I can't generate images. The error is:

（NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs: query : shape=(1, 12288, 8, 40) (torch.float16) key : shape=(1, 12288, 8, 40) (torch.float16) value : shape=(1, 12288, 8, 40) (torch.float16) attn_bias : <class 'NoneType'> p : 0.0 `cutlassF` is not supported because: xFormers wasn't build with CUDA support `flshattF` is not supported because: xFormers wasn't build with CUDA support requires a GPU with compute capability > 7.5 `tritonflashattF` is not supported because: xFormers wasn't build with CUDA support requires A100 GPU `smallkF` is not supported because: xFormers wasn't build with CUDA support dtype=torch.float16 (supported: {torch.float32}) max(query.shape[-1] != value.shape[-1]) > 32 unsupported embed per head: 40）

xFormers does not have CUDA support, so it cannot use cutlassF, flshattF and tritonflashattF operations. This may be because CUDA was disabled during installation or the CUDA version is incompatible.

**Comment by a48475715** [comment]
I have tried to install xFormers with the code you provided, but I also got an error：

error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [339 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/xformers
      copying xformers/test.py -> build/lib.linux-x86_64-cpython-39/xformers
      copying xformers/version.py -> build/lib.linux-x86_64-cpython-39/xformers
      copying xformers/info.py -> build/lib.linux-x86_64-cpython-39/xformers
      copying xformers/_cpp_lib.py -> build/lib.linux-x86_64-cpython-39/xformers
      copying xformers/utils.py -> build/lib.linux-x86_64-cpython-39/xformers

**Comment by a48475715** [comment]
Your step-by-step documentation seems to be a very early version. Has it been updated a lot now? For example, Python versions have been updated. Can you provide a demonstration of the latest version?

**Comment by a48475715** [comment]
It seems that it may be caused by the controlnet plugin. I want to delete it, but deleting files in Gradient is a very headache thing. I still don't know how to batch delete or delete non-empty folders.

**Comment by Cyberes** [comment]
First, create an issue for the `sd-webui-controlnet` plugin about the failure to install the `svglib` pip package -> https://github.com/Mikubill/sd-webui-controlnet/issues

Then come back here if you're still having issues. Feel free to re-open this issue when you're ready.
