### ISSUE TITLE
'AssertionError: extension access disabled because of command line flags'

### ISSUE THREAD

**Issue by gamesdavid** [Engineer-of-Stuff/stable-diffusion-paperspace#110]
Hi, 
when i tried to install an extension buy using 'install from url', i get this error message: 'AssertionError: extension access disabled because of command line flags'.  

I tried several method:
a). remove '--share' under code block Launch the WebUI: port = f'--port {gradio_port}' if gradio_port else '--share' 
result: no gradio link

b). tried under file webui-user.sh add the line: 
export COMMANDLINE_ARGS="--enable-insecure-extension-access"
./webui-user.sh
result: error message: 'AssertionError: extension access disabled because of command line flags'.  

there are some clues in the code mentioned 'insecure-extension-access'
eg.
Code block: Installation and Setup: 

gradio_auth = False                                    # Enable gradio_auth and insecure-extension-access option.

insecure_extension_access = False                      # Force enable extensions without a password.

Code block: Launch the WebUI
auth = f'--gradio-auth {gradio_auth} --enable-insecure-extension-access' if gradio_auth else ''
theme = f'--theme {ui_theme}' if ui_theme else ''
insecure_extension_access = '--enable-insecure-extension-access' if insecure_extension_access else ''

Anyone know how to change the code to allow install extension from URL?  thanks.

**Comment by Cyberes** [comment]
`insecure_extension_access` needs to be `True` in the Settings block.
