### ISSUE TITLE
Error running "Install requirements and download repositories"

### ISSUE THREAD

**Issue by Normiegetout** [Engineer-of-Stuff/stable-diffusion-paperspace#112]
Seeking help figuring out how to fix this error that comes up when I run the Install requirements and download repositories bit
Adding the line "--skip-torch-cuda-test" doesnt do anything

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [4], line 30
     28 # Import launch.py which will automatically run the install script but not launch the WebUI.
     29 import launch
---> 30 launch.prepare_environment()
     32 # Install things for this notebook
     33 get_ipython().system('pip install requests gdown bs4 markdownify')

File /storage/stable-diffusion/stable-diffusion-webui/modules/launch_utils.py:268, in prepare_environment()
    265     run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
    267 if not args.skip_torch_cuda_test and not check_run_python("import torch; assert torch.cuda.is_available()"):
--> 268     raise RuntimeError(
    269         'Torch is not able to use GPU; '
    270         'add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'
    271     )
    273 if not is_installed("gfpgan"):
    274     run_pip(f"install {gfpgan_package}", "gfpgan")

RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

**Comment by ethankongee** [comment]
I also started seeing this issue today.

**Comment by Arroz-11** [comment]
The same thing happens to me, this error appears every now and then, I could never find the solution, I just tried to install everything again, sometimes it worked and sometimes it did not

**Comment by ethankongee** [comment]
Can you try to run this in a new cell and see what it prints?
```
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())
```

I suspect it's an issue with Paperspace

**Comment by Arroz-11** [comment]
> Can you try to run this in a new cell and see what it prints?
> 
> ```
> import torch
> print(torch.cuda.is_available())
> print(torch.cuda.device_count())
> ```
> 
> I suspect it's an issue with Paperspace

I get False and 0

**Comment by ethankongee** [comment]
Ok it's working again now. I'm getting True for `torch.cuda.is_available()`

I'm 90% sure it's a problem with Paperspace.. there's nothing you can do other than writing your own Docker script or move to another more reliable service

**Comment by Normiegetout** [comment]
The service seems to be running normally again after ethank852's post.
Thanks everyone who took part in this discussion. What makes me feel better is that the problem was something out of our hands completely. I really like the Paperspace payment model but I'm not aware of any affordable alternatives.

**Comment by Cyberes** [comment]
I've never had an issue like this with Paperspace. Maybe you caught them during a technical glitch?
