### ISSUE TITLE
About Gradio

### ISSUE THREAD

**Issue by greeberss** [Engineer-of-Stuff/stable-diffusion-paperspace#117]
I hear bad things about Gradio, but is it really disconnect after about 10-ish txttoimg generations bad? Almost every time I use the WebUI, I can generate around 10 images before it error connects out, and I have to rerun the launch WebUI block and reinput everything. I think the most I was able to generate before it disconnected was 20-ish. 

Edit: A4000 seems to be able to handle a lot more generations, but will still disconnect after 20-40 generations. Is there a way to avoid the disconnecting altogether?

**Comment by pskl** [comment]
I have the same issue, I think it has something to do with I/O, I noticed that if I disable preview images, limit interactions that would load images from the Gradio UI it delays crashes considerably.

**Comment by Cyberes** [comment]
What are you using to access your web ui? I use rathole: https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/issues/49#issuecomment-1368494704

**Comment by greeberss** [comment]
I use whatever the default is?
