### ISSUE TITLE
WebUI not creating Gradio links for a few hours?

### ISSUE THREAD

**Issue by greeberss** [Engineer-of-Stuff/stable-diffusion-paperspace#118]
There will be times where I run all the blocks as usual without changing anything, and the WebUI block won't create a Gradio link. It would just say something along the lines of this:

Loading weights [e3c47aedb0] from /storage/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/animagineXLV31_v31.safetensors
Running on local URL:  http://127.0.0.1:7860/
Creating model from config: /storage/stable-diffusion/stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 8.9s (calculate hash: 0.2s, load weights from disk: 0.4s, create model: 0.8s, apply weights to model: 6.5s, calculate empty prompt: 0.7s).

And it just stays that way. I'll try restarting the model, but it still won't work, and I have to wait hours before it starts working again. Anyone else have this problem?

**Comment by m17reardon** [comment]
yep I have been having the same issue. Now xformers won't work 

/storage/stable-diffusion/stable-diffusion-webui
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.0+cu121 with CUDA 1201 (you have 2.2.0+cu121)
    Python  3.10.14 (you have 3.10.10)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

**Comment by Cyberes** [comment]
There's a block to build xformers yourself.

**Comment by m17reardon** [comment]
Yes it is broken right now. I've tried fixing so I'm just keep it Uninstalled. Link came back though

**Comment by greeberss** [comment]
I try to build xformers and get this

error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [279 lines of output]
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/xformers
copying xformers/checkpoint.py -> build/lib.linux-x86_64-cpython-310/xformers
copying xformers/info.py -> build/lib.linux-x86_64-cpython-310/xformers
copying xformers/_cpp_lib.py -> build/lib.linux-x86_64-cpython-310/xformers
copying xformers/_deprecation_warning.py -> build/lib.linux-x86_64-cpython-310/xformers
copying xformers/utils.py -> build/lib.linux-x86_64-cpython-310/xformers
copying xformers/test.py -> build/lib.linux-x86_64-cpython-310/xformers
copying xformers/init.py -> build/lib.linux-x86_64-cpython-310/xformers
copying xformers/attn_bias_utils.py -> build/lib.linux-x86_64-cpython-310/xformers
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/flash_attn_triton_og.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/fused_softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/flash_attn_interface.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/flash_blocksparse_attn_interface.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/flash_attn_triton.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/flash_blocksparse_attention.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
copying xformers/_flash_attn/bert_padding.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn
creating build/lib.linux-x86_64-cpython-310/xformers/helpers
copying xformers/helpers/hierarchical_configs.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
copying xformers/helpers/test_utils.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
copying xformers/helpers/init.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
copying xformers/helpers/timm_sparse_attention.py -> build/lib.linux-x86_64-cpython-310/xformers/helpers
creating build/lib.linux-x86_64-cpython-310/xformers/sparse
copying xformers/sparse/csr_tensor.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
copying xformers/sparse/blocksparse_tensor.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
copying xformers/sparse/_csr_ops.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
copying xformers/sparse/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
copying xformers/sparse/init.py -> build/lib.linux-x86_64-cpython-310/xformers/sparse
creating build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/fused_linear_layer.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/k_fused_matmul_fw.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/k_softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/dropout.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/k_fused_matmul_bw.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/k_activations.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/k_dropout.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/layer_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/vararg_kernel.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/k_layer_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/init.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
copying xformers/triton/softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/triton
creating build/lib.linux-x86_64-cpython-310/xformers/profiler
copying xformers/profiler/profiler_dcgm_impl.py -> build/lib.linux-x86_64-cpython-310/xformers/profiler
copying xformers/profiler/profiler.py -> build/lib.linux-x86_64-cpython-310/xformers/profiler
copying xformers/profiler/profiler_dcgm.py -> build/lib.linux-x86_64-cpython-310/xformers/profiler
copying xformers/profiler/api.py -> build/lib.linux-x86_64-cpython-310/xformers/profiler
copying xformers/profiler/init.py -> build/lib.linux-x86_64-cpython-310/xformers/profiler
copying xformers/profiler/device_limits.py -> build/lib.linux-x86_64-cpython-310/xformers/profiler
copying xformers/profiler/slow_ops_profiler.py -> build/lib.linux-x86_64-cpython-310/xformers/profiler
creating build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_triton_softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_sequence_parallel_fused.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_triton_layernorm.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_multi_head_dispatch.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_attn_decoding.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_nystrom_utils.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_transformer.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_revnet.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_triton_blocksparse.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_indexing.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_sp24.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_swiglu.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_mem_eff_attention.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_tiled_matmul.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/init.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_blocksparse_transformers.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_triton_dropout.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_sddmm.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_causal_blocksparse.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_core.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
copying xformers/benchmarks/benchmark_triton_fused_linear.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks
creating build/lib.linux-x86_64-cpython-310/xformers/factory
copying xformers/factory/block_factory.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
copying xformers/factory/model_factory.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
copying xformers/factory/init.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
copying xformers/factory/weight_init.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
copying xformers/factory/block_configs.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
copying xformers/factory/hydra_helper.py -> build/lib.linux-x86_64-cpython-310/xformers/factory
creating build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/ipc.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/modpar_layers.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/rope_padded.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/unbind.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/sequence_parallel_fused_ops.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/swiglu_op.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/indexing.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/differentiable_collectives.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/seqpar.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/common.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/sp24.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/tiled_matmul.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/init.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
copying xformers/ops/rmsnorm.py -> build/lib.linux-x86_64-cpython-310/xformers/ops
creating build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/input_projection.py -> build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/residual.py -> build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/simplicial_embedding.py -> build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/activations.py -> build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/init.py -> build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/reversible.py -> build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/multi_head_dispatch.py -> build/lib.linux-x86_64-cpython-310/xformers/components
copying xformers/components/patch_embedding.py -> build/lib.linux-x86_64-cpython-310/xformers/components
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
copying xformers/_flash_attn/layers/rotary.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
copying xformers/_flash_attn/layers/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
copying xformers/_flash_attn/layers/patch_embed.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/layers
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/losses
copying xformers/_flash_attn/losses/cross_entropy.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/losses
copying xformers/_flash_attn/losses/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/losses
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/falcon.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/opt.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/gptj.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/llama.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/gpt_neox.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/baichuan.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/bigcode.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/vit.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/bert.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/btlm.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
copying xformers/_flash_attn/models/gpt.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/models
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
copying xformers/_flash_attn/modules/block.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
copying xformers/_flash_attn/modules/embedding.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
copying xformers/_flash_attn/modules/mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
copying xformers/_flash_attn/modules/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
copying xformers/_flash_attn/modules/mha.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/modules
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
copying xformers/_flash_attn/utils/generation.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
copying xformers/_flash_attn/utils/pretrained.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
copying xformers/_flash_attn/utils/distributed.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
copying xformers/_flash_attn/utils/benchmark.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
copying xformers/_flash_attn/utils/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/utils
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
copying xformers/_flash_attn/ops/fused_dense.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
copying xformers/_flash_attn/ops/layer_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
copying xformers/_flash_attn/ops/activations.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
copying xformers/_flash_attn/ops/rms_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
copying xformers/_flash_attn/ops/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops
creating build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
copying xformers/_flash_attn/ops/triton/k_activations.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
copying xformers/_flash_attn/ops/triton/layer_norm.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
copying xformers/_flash_attn/ops/triton/cross_entropy.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
copying xformers/_flash_attn/ops/triton/mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
copying xformers/_flash_attn/ops/triton/linear.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
copying xformers/_flash_attn/ops/triton/rotary.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
copying xformers/_flash_attn/ops/triton/init.py -> build/lib.linux-x86_64-cpython-310/xformers/_flash_attn/ops/triton
creating build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
copying xformers/benchmarks/LRA/batch_submit.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
copying xformers/benchmarks/LRA/batch_fetch_results.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
copying xformers/benchmarks/LRA/init.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
copying xformers/benchmarks/LRA/run_with_submitit.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
copying xformers/benchmarks/LRA/run_grid_search.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
copying xformers/benchmarks/LRA/run_tasks.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA
creating build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
copying xformers/benchmarks/LRA/code/model_wrapper.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
copying xformers/benchmarks/LRA/code/dataset.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
copying xformers/benchmarks/LRA/code/init.py -> build/lib.linux-x86_64-cpython-310/xformers/benchmarks/LRA/code
creating build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/ck.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/flash.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/dispatch.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/decoder.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/common.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/small_k.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/ck_splitk.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/attn_bias.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/init.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/triton_splitk.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/cutlass.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
copying xformers/ops/fmha/ck_decoder.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/fmha
creating build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
copying xformers/ops/_triton/sequence_parallel_fused_kernels.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
copying xformers/ops/_triton/rope_padded_kernels.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
copying xformers/ops/_triton/tiled_matmul_kernels.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
copying xformers/ops/_triton/k_index_select_cat.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
copying xformers/ops/_triton/init.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
copying xformers/ops/_triton/rmsnorm_kernels.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
copying xformers/ops/_triton/k_scaled_index_add.py -> build/lib.linux-x86_64-cpython-310/xformers/ops/_triton
creating build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/_sputnik_sparse.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/lambda_layer.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/visual.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/blocksparse.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/sparsity_config.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/nystrom.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/scaled_dot_product.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/core.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/fourier_mix.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/random.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/attention_patterns.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/ortho.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/attention_mask.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/local.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/pooling.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/utils.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/init.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/compositional.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/linformer.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/global_tokens.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
copying xformers/components/attention/favor.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention
creating build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
copying xformers/components/positional_embedding/param.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
copying xformers/components/positional_embedding/vocab.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
copying xformers/components/positional_embedding/rotary.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
copying xformers/components/positional_embedding/init.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
copying xformers/components/positional_embedding/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
copying xformers/components/positional_embedding/sine.py -> build/lib.linux-x86_64-cpython-310/xformers/components/positional_embedding
creating build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
copying xformers/components/feedforward/conv_mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
copying xformers/components/feedforward/fused_mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
copying xformers/components/feedforward/mixture_of_experts.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
copying xformers/components/feedforward/mlp.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
copying xformers/components/feedforward/init.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
copying xformers/components/feedforward/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/feedforward
creating build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
copying xformers/components/attention/feature_maps/init.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
copying xformers/components/attention/feature_maps/base.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
copying xformers/components/attention/feature_maps/softmax.py -> build/lib.linux-x86_64-cpython-310/xformers/components/attention/feature_maps
running build_ext
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/tmp/pip-wheel-chpzsbkp/xformers_ec4eafc23d6741d28f2babe809fe940b/setup.py", line 485, in
setuptools.setup(
File "/usr/local/lib/python3.10/dist-packages/setuptools/init.py", line 104, in setup
return distutils.core.setup(**attrs)
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 184, in setup
return run_commands(dist)
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 200, in run_commands
dist.run_commands()
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
self.run_command(cmd)
File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 967, in run_command
super().run_command(command)
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.10/dist-packages/wheel/bdist_wheel.py", line 368, in run
self.run_command("build")
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
self.distribution.run_command(command)
File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 967, in run_command
super().run_command(command)
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build.py", line 132, in run
self.run_command(cmd_name)
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
self.distribution.run_command(command)
File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 967, in run_command
super().run_command(command)
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 91, in run
_build_ext.run(self)
File "/usr/local/lib/python3.10/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
self.build_extensions()
File "/tmp/pip-wheel-chpzsbkp/xformers_ec4eafc23d6741d28f2babe809fe940b/setup.py", line 442, in build_extensions
super().build_extensions()
File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 525, in build_extensions
_check_cuda_version(compiler_name, compiler_version)
File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 413, in _check_cuda_version
raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (11.6) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions.

  [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for xformers

**Comment by greeberss** [comment]
> There will be times where I run all the blocks as usual without changing anything, and the WebUI block won't create a Gradio link. It would just say something along the lines of this:
> 
> Loading weights [e3c47aedb0] from /storage/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/animagineXLV31_v31.safetensors Running on local URL: http://127.0.0.1:7860/ Creating model from config: /storage/stable-diffusion/stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml Applying attention optimization: Doggettx... done. Model loaded in 8.9s (calculate hash: 0.2s, load weights from disk: 0.4s, create model: 0.8s, apply weights to model: 6.5s, calculate empty prompt: 0.7s).
> 
> And it just stays that way. I'll try restarting the model, but it still won't work, and I have to wait hours before it starts working again. Anyone else have this problem?

This issue seems to be happening more frequently now

**Comment by greeberss** [comment]
Gradio bad
