### ISSUE TITLE
NansException on Inpainting

### ISSUE THREAD

**Issue by Tessabyte** [Engineer-of-Stuff/stable-diffusion-paperspace#121]
**Error Message:** 

NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

**What I was trying to do:**

Inpainting with an image upload in "img2img --> generation --> inpaint" tabs

**Other:**

Using "upcast cross-attention layer to float32" and the following command-line arguments in webui-user.bat: --share --enable-insecure-extension-access --no-half --no-half-vae (on only free Paperspace machines and "Growth" plan)

**Raw Error:**

![Screenshot 2024-06-05 112636](https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/assets/131934298/cdb0c0c8-ce30-4da8-b0df-3e85d2fb5e04)

**Comment by Cyberes** [comment]
Pretty common issue, sorry. Try a different model to see if it's related to that and keep tweaking the settings.

You'll have to seek further help with the WebUI project.
