### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by Kartich** [Engineer-of-Stuff/stable-diffusion-paperspace#13]
I can`t run it because of the "UsageError: Unknown variable 'free_tier'"

**Comment by swcrazyfan** [comment]
Which notebook are you running?

**Comment by Boymerkz** [comment]
Same issue running StableDiffusionUI_Voldemort_paperspace

**Comment by Boymerkz** [comment]
> I can`t run it because of the "UsageError: Unknown variable 'free_tier'"

notice there's no space that's the issue when uncommenting make sure theres no space so do this 

# Paid Tier
free_tier = False
model_storage_dir = '/storage/models'
repo_storage_dir = '/notebooks'

NOT 
# Paid Tier
 free_tier = False
 model_storage_dir = '/storage/models'
 repo_storage_dir = '/notebooks'

 Notice there's a space in the bottom one remove all the spaces.

**Comment by Kartich** [comment]
the problem has been sovled,thanks for your help

**Comment by Cyberes** [comment]
Thanks guys
