### ISSUE TITLE
No module named 'fastapi'

### ISSUE THREAD

**Issue by Niutonian** [Engineer-of-Stuff/stable-diffusion-paperspace#14]
Hello, I have a problem launching the Web-UI, 
Could you tell me where the problem comes from?

```
/notebooks/stable-diffusion-webui
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/webui.py", line 7, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
```

Thank you

**Comment by Niutonian** [comment]
Ok, I will, 
sorry for the late reply I was travelling, 
I will try updating the repo and report back, 
Best, 

Arnaud

**Comment by Niutonian** [comment]
Hello, 
sorry to bother but it is still now working, 
I still get the same error when I launched the webui.
This is the tutorial I'm using, 
could you take a look at it and maybe see if a step is missing, 

[Link to tutorial](https://proximacentaurib.notion.site/A-guide-to-getting-started-with-the-paperspace-port-of-AUTOMATIC1111-s-web-UI-for-ppl-who-get-nervou-b83c2213f17e452e8b0e37ba64fe9758)

Thank you

**Comment by Cyberes** [comment]
Are you running every block up to the Launch the WebUI block? You need to run every block or you won't install everything (you can skip the Download the Model section if you've already downloaded what you want).

**Comment by Niutonian** [comment]
Hello, I made a screen capture of the paperspace until it stalls when I get to the webui. 
I hope this will clear up everything. 


https://github.com/Niutonian/paperspace/blob/main/stableDiffusion_paperSpace.mp4

**Comment by Cyberes** [comment]
Update the notebook, delete `stable-diffusion-webui`, restart the machine. Then reinstall. Maybe that will fix it?

**Comment by Cyberes** [comment]
Actually, here's the problem.

![Screenshot from 2022-11-03 10-58-29](https://user-images.githubusercontent.com/64224601/199786368-87058212-911c-4236-a85a-bf08c070291f.png)

You're using the latest webui version but not the latest notebook. The current way to install dependencies is like this:
```python
# Import launch.py which will automatically run the install script but not launch the WebUI.
# They require a few specific external git repo commits so we have to do it their way. 
import launch
launch.prepare_enviroment()
```
Just update your notebook and that should fix it.
