### ISSUE TITLE
i don't get how restart the machin 

### ISSUE THREAD

**Issue by flover2102** [Engineer-of-Stuff/stable-diffusion-paperspace#15]
after i restart i  don't see how restart the machin , i see 1st  line that say "You must reinstall everything each time you restart the machine" 
so i try to use Reset storage tool for that w/ all Uncomment but i get an error

**Comment by Cyberes** [comment]
Don't touch anything in the Tools section. Start from the beginning of the notebook and run each cell (skip the model download cells you want). The notebook will do everything for you. The block that's labeled "Launch" will start the webui and you will get a link. Also, make sure to uncomment the free or paid section in the very first block.
