### ISSUE TITLE
a script "wildcards.py" is obsolated

### ISSUE THREAD

**Issue by yife** [Engineer-of-Stuff/stable-diffusion-paperspace#19]
This notebook try to download and use wildcards.py scripts, but it seems obsolated and it won't work anymore.

- https://github.com/jtkelm2/stable-diffusion-webui-1/blob/main/scripts/wildcards.py
- https://github.com/jtkelm2/stable-diffusion-webui-1

Maybe you should replace it with other repositories, or remove it.

**Comment by Cyberes** [comment]
Fixed a67f61a4d8ae48cae0b8c68905ab8d14929fa527
