### ISSUE TITLE
Where to start the notebook with commandline arguments?

### ISSUE THREAD

**Issue by githubartman** [Engineer-of-Stuff/stable-diffusion-paperspace#2]
I asked on the main repo of Automatic1111 but they couldnt help me so far: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/1717

Where do I put commandline arguments that I want the repo to start with, like --medvram? Help would be greatly appreciated

**Comment by Cyberes** [comment]
AH DONT DO NGROK!!! Someone said Paperspace locked their account and asked for an explanation about why they were using a tunneling proxy. You have to self-host a tunneling proxy like [sish](https://github.com/antoniomika/sish) or [rathole](https://github.com/rapiz1/rathole). I use rathole and it works well but sish is over ssh.

And yeah, I think you got it. Launch args go in the "Launch the WebUI" block.
