### ISSUE TITLE
Textual Inversion with xformers error

### ISSUE THREAD

**Issue by corytaitchison** [Engineer-of-Stuff/stable-diffusion-paperspace#20]
When attempting to start training an embedding with the xformers flag active, I get this error:
```
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/webui.py", line 53, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/modules/textual_inversion/ui.py", line 31, in train_embedding
    embedding, filename = modules.textual_inversion.textual_inversion.train_embedding(*args)
  File "/notebooks/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 300, in train_embedding
    loss = shared.sd_model(x, c)[0]
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 879, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/notebooks/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 1030, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
Note that it works fine when not using xformers, and the other tools work fine with xformers (text2img etc.). I am using the A4000 GPU.

**Comment by Cyberes** [comment]
If xformers installs and you don't see any errors when you start the program then that's a webui problem. I'd open an issue there.

**Comment by corytaitchison** [comment]
Hi, just an update: I think the issue is coming from the version of torch. 

If I disable the xformers flag, having run the xformers install scripts, then I still get the same issue. 

But if I first run `pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio --extra-index-url https://download.pytorch.org/whl/cu113` then there is no error, but xformers no longer works.

Note that after running the xformers install, I get torch 1.13.

**Comment by Yardanico** [comment]
Having the same issue, read a few similar issues in the automatic's repo but they don't really have solutions.

**Comment by Cyberes** [comment]
Skill issue.

But seriously, I got the same error you did when trying to train an embed. Try building an xformers wheel using the packages installed with
```
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```
and see what happens. Do you still get
```
/usr/local/lib/python3.9/dist-packages/xformers/_C.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE
WARNING: /usr/local/lib/python3.9/dist-packages/xformers/_C.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE
Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
```
on startup?

**Comment by Yardanico** [comment]
okay, that seems to work, thanks.

**Comment by Cyberes** [comment]
Sweet. Guess I'll go recompile the xformers wheels for a third time...

**Comment by Yardanico** [comment]
@Cyberes it is quite fast to recompile them with after `pip install ninja` and with:
```
XFORMERS_DISABLE_FLASH_ATTN=1 NVCC_FLAGS="--use_fast_math -DXFORMERS_MEM_EFF_ATTENTION_DISABLE_BACKWARD" MAX_JOBS=8 python setup.py install
```

(taken from xformers issues)

**Comment by Yardanico** [comment]
Flags taken from 
https://github.com/facebookresearch/xformers/pull/482
and 
https://github.com/facebookresearch/xformers/issues/481#issuecomment-1277530256

**Comment by Cyberes** [comment]
That's great!

**Comment by corytaitchison** [comment]
> Skill issue.
> 
> But seriously, I got the same error you did when trying to train an embed. Try building an xformers wheel using the packages installed with
> 
> ```
> pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
> ```
> 
> and see what happens. Do you still get
> 
> ```
> /usr/local/lib/python3.9/dist-packages/xformers/_C.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE
> WARNING: /usr/local/lib/python3.9/dist-packages/xformers/_C.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE
> Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
> ```
> 
> on startup, any errors when trying to generate, or errors when starting training of an embed?

Works for me, no errors

**Comment by Cyberes** [comment]
Great, now go impress the normies. They seem to struggle with xformers.
