### ISSUE TITLE
Need to compile C++ extensions to get sparse attention suport.

### ISSUE THREAD

**Issue by Hypsor** [Engineer-of-Stuff/stable-diffusion-paperspace#21]
Hi, I've successfully run webUI, but im having issues when running with xFormers:

/notebooks/stable-diffusion-webui
/usr/local/lib/python3.9/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
WARNING:root:WARNING: /usr/local/lib/python3.9/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop

------
already ran build-xformers block, but nothing changes

**Comment by Cyberes** [comment]
What's your GPU? I encountered this issue and solved it by rebuilding the xformers wheel (see https://github.com/Cyberes/xformers-compiled/releases/tag/A4000-Oct-28-2022) but I've only done it for the A4000. I'm a little surprised it's still giving you that error after you built it again.

Here's how to build the wheel:
```bash
pip install ninja
python setup.py bdist_wheel --universal
find $1 -name *.whl
```
You should see the path to the .whl file after that's done running. Then do `pip install --force-reinstall [path to .whl file]`. Hopefully that fixes it.

**Comment by Tsalnor** [comment]
I've rebuilt the free GPUs. The M4000 one didn't seem to work for some reason, but the rest all worked when I tested them. I've uploaded them here for anyone to use.
https://mega.nz/folder/AnYgxRSY#eReKIz7wESrOhlS4-uAegw

**Comment by Cyberes** [comment]
Damn dude, that's great. I'll upload them to https://github.com/Cyberes/xformers-compiled/releases
