### ISSUE TITLE
is it possible to support Krita or GIMP plugin?

### ISSUE THREAD

**Issue by Xz3r0-M** [Engineer-of-Stuff/stable-diffusion-paperspace#27]
https://github.com/Interpause/auto-sd-krita
https://github.com/blueturtleai/gimp-stable-diffusion
https://www.flyingdog.de/sd/en/

i don't understand about the code.
they only create Google Colab script.
so, is it possible for Paperspace script to have the same function?

**Comment by Cyberes** [comment]
I'll see if I have the time to do this. Can't promise anything unfortunately.

**Comment by Xz3r0-M** [comment]
i got it, much easier if use this extension version Krita plugin: https://github.com/Interpause/auto-sd-paint-ext
just upload some files to Paperspace, add `--api --listen` in launch and delete `--gradio-debug`.
