### ISSUE TITLE
Openjourny ckpt file?

### ISSUE THREAD

**Issue by sonicviz** [Engineer-of-Stuff/stable-diffusion-paperspace#30]
Hi, 
Testing out paperspace now, using this as a testbed. 
Working great so far, thanks!

I was wondering if there was torrent of https://huggingface.co/prompthero/openjourney ckpt file, or you need to use the huggingspace tokem method to connect and download it?
Would be good to have that method as an option in the notebook I think, as it's quite flexible as it is.

**Comment by Cyberes** [comment]
I've been putting other models on this page: https://cyberes.github.io/stable-diffusion-models/

But I think it would be a good idea to add an easy way to download models from huggingface.

**Comment by sonicviz** [comment]
awesome, thanks!

**Comment by Cyberes** [comment]
I added a model downloader. See 0a90822768f5542469719a099b882993cd683791
