### ISSUE TITLE
AttributeError: module 'launch' has no attribute 'prepare_enviroment'

### ISSUE THREAD

**Issue by fritzy3** [Engineer-of-Stuff/stable-diffusion-paperspace#35]
Hi,

I downloaded now (20 minutes ago) the files and uploaded the notebook to paperspace (new gradient notebook from scratch). removed relevant # for the pro plan. First 2 cells executed properly but running "Install requirements and download repositories" I get this error (checked twice):

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 20>()
     17 # Import launch.py which will automatically run the install script but not launch the WebUI.
     18 # They require a few specific external git repo commits so we have to do it their way. 
     19 import launch
---> 20 launch.prepare_enviroment()
     22 # The installer isn't installing deepdanbooru right now so we'll do it manually
     23 if activate_deepdanbooru:

AttributeError: module 'launch' has no attribute 'prepare_enviroment'

**Comment by tizio04** [comment]
Someone just opened a pull request [here](https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/pull/34).
In the meantime you can fix the typo by yourself, edit line 20 and add the missing "n" in enviroNment, like this:
`launch.prepare_environment()`

**Comment by start1002** [comment]
Someone just opened a pull request https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/pull/34.
In the meantime you can fix the typo by yourself, edit line 20 and add the missing "n" in enviroNment, like this:
launch.prepare_environment()

**Comment by Cyberes** [comment]
Yup, merged. Thanks guys.
