### ISSUE TITLE
How can I get the model from Google Cloud Disk?

### ISSUE THREAD

**Issue by start1002** [Engineer-of-Stuff/stable-diffusion-paperspace#38]
Sorry, I don’t know English, so I can only use software to translate, the thing is like this, I have been using code to download files in Google Cloud Disk, but now it fails, what should I do?
code show as below：
%store -r symlink_to_notebooks model_storage_dir repo_storage_dir
!pip install --upgrade --no-cache-dir gdown
!gdown "Google Drive Link" -O "{model_storage_dir}/file name" --no-cookies
![QQ截图20221211172602](https://user-images.githubusercontent.com/116997173/206896022-f1a7328e-b434-40d2-bb71-a51d78b93fa0.png)
I checked Google Drive and found nothing wrong.
![QQ图片20221211172840](https://user-images.githubusercontent.com/116997173/206896083-24e3d347-7fc5-4929-8395-456bc347ccef.png)
Thanks!

**Comment by ackl** [comment]
try adding a query param `confirm=t` to the google drive url

(this is done automatically if you just use the Automated Model Downloader cell - at the very bottom of the notebook)
