### ISSUE TITLE
How to enable extensions?

### ISSUE THREAD

**Issue by fritzy3** [Engineer-of-Stuff/stable-diffusion-paperspace#42]
I hope it's ok to ask here. didn't find another place.

I'm trying to install an extension and I'm getting an error:
"AssertionError: extension access disabled because of command line flags"

I've tried enabling gradio_auth and/or insecure access from the first block. I couldn't figure out where to set "me:password". in the first block is seems it's true/false. In different lines in the launch webui block it also didn't work.
I thought the insecure access should skip this issue, but I still got the error.

**Comment by Cyberes** [comment]
Have you updated to the latest version of the notebook? There's a block in the Tools section to do it for you.

To enable extensions the right way, set `gradio_auth = username:password`. To enable extensions the lazy way, set `insecure_extension_access = True`.
