### ISSUE TITLE
About NovelAI Leak's vae files.

### ISSUE THREAD

**Issue by gihepa988** [Engineer-of-Stuff/stable-diffusion-paperspace#45]
NovelAI Leak does not recognize vae files correctly even if they are placed in the specified directory (/storage/models/).
Is there a difference in the location of the file? Is there a specific file name? 
Please respond if you can.

**Comment by Cyberes** [comment]
Which files are you referring to?

**Comment by gihepa988** [comment]
> 

NovelAI vae file. I prepared this file by myself.
I put it in the same directory as the model file (.ckpt) with the same name, but it is not recognized. I even rewrote "true" in the first configuration cell...

**Comment by gihepa988** [comment]
Sorry, I put the vae files in the vae directory and webui recognized them. It seems that it should not be in the same directory as the model files. Sorry for the inconvenience.

**Comment by Cyberes** [comment]
Glad you got it sorted out.
