### ISSUE TITLE
The automated model downloader block cuts off the magnet url in the middle if there's a `-` or `_`

### ISSUE THREAD

**Issue by BLucky-gh** [Engineer-of-Stuff/stable-diffusion-paperspace#46]
The magnet link
 ```
magnet:?xt=urn:btih:ed9f0e3f849d7119107ef4e072c6abeb129e1a51&dn=r34_e4.ckpt&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2f9.rarbg.com%3a2810%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a6969%2fannounce&tr=http%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2fopentracker.i2p.rocks%3a6969%2fannounce&tr=https%3a%2f%2fopentracker.i2p.rocks%3a443%2fannounce&tr=udp%3a%2f%2fopen.stealth.si%3a80%2fannounce&tr=udp%3a%2f%2ftracker.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2ftracker2.dler.org%3a80%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.moeking.me%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.dler.org%3a6969%2fannounce&tr=udp%3a%2f%2fpublic.tracker.vraphim.com%3a6969%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2fmovies.zsw.ca%3a6969%2fannounce&tr=udp%3a%2f%2fipv4.tracker.harry.lu%3a80%2fannounce&tr=udp%3a%2f%2ffe.dealclub.de%3a6969%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce
``` 
gets cropped as `magnet:?xt=urn:btih:ed9f0e3f849d7119107ef4e072c6abeb129e1a51&dn=r34` by the regex which leads to a failed download.

Changing the regex from `magnet:\?xt=urn:btih:[_A-Za-z0-9&=%.]*` to `magnet:\?xt=urn:btih:[_A-Za-z0-9\-_&=%.]*` (also match the literal `-` and `_`) seems to help in this specific case, but I'm not sure if this will result in any issues with other URIs

~~Other small issue: the line after `!aria2c <...>` says `exit` without the parentheses, which leads to not exiting and then throwing an exception when the GDrive link variable is not set, adding the parentheses (`exit()`) fixes the issue~~
EDIT: `exit()` stops the kernel, so instead it would be better to add another `elif magnet_match: pass` to the final `elif` block would be enough to avoid a misleading `Downloaded!` followed by a `Failed to parse URI`

There's also the small QoL issue that the `apt update` and `apt install aria` aren't behind an `!if` which leads to it being reinstalled on every run

I can make a pull request with the changes if needed

**Comment by Cyberes** [comment]
Good catch on the regex issue! One tiny suggestion: use `magnet:\?xt=urn:btih:[_A-Za-z0-9\-&=%.]*` so you don't repeat the underscore in the literals.

And I didn't know that `exit()` stops the kernal. Thanks.

For the `apt install aria` it seems I forgot to copy this code to the downloader:
```bash
!if [ $(dpkg-query -W -f='${Status}' aria2 2>/dev/null | grep -c "ok installed") = 0 ]; then sudo apt update && sudo apt install -y aria2; fi
```

A pull request would be fantastic.

**Comment by BLucky-gh** [comment]
> use magnet:\?xt=urn:btih:[_A-Za-z0-9\-&=%.]* so you don't repeat the underscore in the literals.

thanks for pointing out, didn't notice I specified it twice

as for `exit()`, it turned out that `exit()` doesn't do *anything*, doesn't even raise a `NameError` which is weird, and the reason it stopped the kernel was because I typed `sys.exit()` out of habit. There seems to be no way to exit early from the cell without stopping the kernel.

I'm gonna make a pull request with the 2 changes later today

**Comment by BLucky-gh** [comment]
Small edit: turns out `exit()` does stop the kernel, ***but*** only after the cell is finished, so it will not exit early, it will just stop the kernel after the current cell is finished *and* it also resets the environment unlike `sys.exit()`, so the user has to go back to the first cell and set the variables again

**Comment by Cyberes** [comment]
Cool, I'll take a look at it.

> There seems to be no way to exit early from the cell without stopping the kernel.

You could raise an exception but that shows a big red error...
