### ISSUE TITLE
Notebook for IPU machines

### ISSUE THREAD

**Issue by eaglgenes101** [Engineer-of-Stuff/stable-diffusion-paperspace#48]
As of recently, [Paperspace now offers notebook machines with Graphcore IPUs](https://docs.paperspace.com/gradient/machines#ipu-machines), and the specs are impressive. 104 GB RAM is more than the combined memory and VRAM of most of the GPU machines, and if the TFlop numbers are accurate and representative, then they absolutely blast the GPU machines out of the water in computing power. Best of all, all of this is applicable to free instances which don't require a premium subscription to access, so no money is needed to take advantage of these absolutely busted specs. 

Now, Stability AI's Stable Diffusion implementation isn't written to take advantage of IPUs (`.cuda()` calls everywhere, oh my), but there are other implementations that can use them. Graphcore covers one way of doing so at https://www.graphcore.ai/posts/how-to-run-stable-diffusion-inference-on-ipus-with-paperspace . Maybe this can be spruced up into a fully-featured notebook script?

**Comment by Cyberes** [comment]
The notebooks linked in the post aren't loading for me, something about a "Unexpected error". Can you download them and attach them to a reply?

**Comment by eaglgenes101** [comment]
I found a repo with the notebook sources: https://github.com/gradient-ai/Graphcore-HuggingFace . The "front page" ipynb files that the links in that blog post open are in "/notebooks/stable-diffusion/".

**Comment by eaglgenes101** [comment]
How's this one doing so far?

**Comment by Cyberes** [comment]
This notebook is more focused on the stable-diffusion-webui, which I don't think could easily be ported to IPU. But if you get something running, post a link here and I'll add it to the README.md
