### ISSUE TITLE
After the update, the webpage cannot save the picture

### ISSUE THREAD

**Issue by start1002** [Engineer-of-Stuff/stable-diffusion-paperspace#49]
![QQ截图20230101174454](https://user-images.githubusercontent.com/116997173/210166774-b17710de-52cb-45ce-a709-0035f7c7cf8a.png)
![QQ截图20230101174643](https://user-images.githubusercontent.com/116997173/210166781-e76f9ebb-df9e-49ec-8e54-d4c0fb4679a5.png)
As shown in the figure, after the image is generated, it disappears, and the entire page stops responding. Clicking the Generate button again does not respond. How can I solve this problem?

PS: I can't speak English, so I can only use machine translation. I'm sorry if it bothers your reading.

**Comment by Cyberes** [comment]
You just encountered the infamous Gradio bug. Basically, Gradio runs a reverse proxy service that connects your WebUI interface to the internet. Unfortunately, their proxy service is really shitty and can't proxy a file larger than 2MB. The WebUI program integrates ngrok to fix this issue.

Unfortunately, Paperspace locks your account for using any tunneling proxy service such as ngrok (who knows how many they explicitly ban). There is literally no easy solution for this. Personally, what I do is run a [rathole](https://github.com/rapiz1/rathole) server on a $5 DigitalOcean cloud VPS which I've had great success with. You've got to host your own server that Paperspace doesn't know about.

Here's some more tunneling proxy servers: https://github.com/anderspitman/awesome-tunneling

I'm sorry, but you're on your own with this.

https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/7b17e4965ad72f73dbf06b72b0158f94d8c48e68/docs/Tunneling%20Proxy%20for%20Paperspace.md

**Comment by ShadeRedeye** [comment]
try rollback gradio in requirement file to 3.9 and it should be work.

**Comment by Cyberes** [comment]
https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/7b17e4965ad72f73dbf06b72b0158f94d8c48e68/docs/Tunneling%20Proxy%20for%20Paperspace.md

**Comment by ShadeRedeye** [comment]
it's already fixed for me,try this new method that recently commit by auto, --gradio-queue,also to make sure remove --gradio-debug,since it break progress bar for ui

**Comment by Cyberes** [comment]
I was wondering why the progress bar was broken!
