### ISSUE TITLE
When starting the webui, the website for AI painting cannot appear

### ISSUE THREAD

**Issue by start1002** [Engineer-of-Stuff/stable-diffusion-paperspace#50]
![QQ截图20230102142924](https://user-images.githubusercontent.com/116997173/210201186-1374df37-a554-4c7e-8bd6-c9feee43455c.png)
![QQ截图20230102144015](https://user-images.githubusercontent.com/116997173/210201190-9ab82cf4-1623-425c-ae6c-ac9edc8e4191.png)
As shown in the figure, after starting the webui, the usual AI painting URL is lost. Restarting the kernel or deleting the laptop and reinstalling cannot solve this problem. What should I do?

PS: I can't speak English, so I can only use machine translation. I'm sorry if it bothers your reading.

Now I can't use AI to paint, which is very painful. I sincerely ask for the help of insiders. Thank you very much :(

PS2：Enter a new cell:

pip install gradio==3.9.0

Then run. After running, restart the kernel and run the WebUI again

**Comment by Cyberes** [comment]
Set `gradio_port` in settings to `False`.

**Comment by start1002** [comment]
> 在设置中设置为 。`gradio_port``False`
![QQ截图20230102151721](https://user-images.githubusercontent.com/116997173/210203193-1f2ff9ef-328d-49a6-b867-d15b592e043d.png)
gradio_ port = False

It has always been like this, and it is still invalid

**Comment by start1002** [comment]
> 在设置中设置为 。`gradio_port``False`

Enter a new cell:

pip install gradio==3.9.0

Then run. After running, restart the kernel and run the WebUI again

**Comment by Cyberes** [comment]
Huh, did they break something again? I'll see what happens with our "upstream" but I might add that to the installer.

**Comment by SylvianHemus** [comment]
Having the same issue, script probably needs an upgrade. Guessing syntax of something changed
