### ISSUE TITLE
How can I stop the generation of pip folders?

### ISSUE THREAD

**Issue by start1002** [Engineer-of-Stuff/stable-diffusion-paperspace#54]
![-9lddQ2r-412K26T3cS158-e1](https://user-images.githubusercontent.com/116997173/212073365-b960dbcd-e978-4dd6-ac3e-b2bb3f938e8d.png)
I use the subscription of $8 per month, so my storage capacity is 15G. In order to not exceed the limit of 15G, I will keep the common AI painting model at about 14G, which has been the case since a few months ago. However, after the latest update, my storage space will always be 2G more, which makes me very headache. How can I solve it? Thank you very much:（

I have tried the following operation, but it is invalid:（
![-9lddQ2r-8bcbK18T1kSfq-9g](https://user-images.githubusercontent.com/116997173/212073407-647798da-c374-4eff-bd12-4482ed910c67.png)

**Comment by Cyberes** [comment]
Can you redownload and reinstall the notebook? Also delete the directory `/storage/pip/cache`.

If `pip_cache_dir` is set to `None` then the wheels won't be cached. If `/storage/pip/cache` isn't recreated after you redownload the notebook then the cache dir feature is disabled. I just tested it again and it's working as expected for me.

**Comment by start1002** [comment]
> 是否可以重新下载并重新安装笔记本？同时删除目录 。`/storage/pip/cache`
> 
> 如果设置为 ，则不会缓存轮子。如果在重新下载笔记本后未重新创建，则禁用缓存目录功能。我刚刚再次测试了它，它对我来说按预期工作。`pip_cache_dir``None``/storage/pip/cache`

Thank you for your answer... My models are all in my notebook and need to be downloaded again after deletion, so there is no reset
