### ISSUE TITLE
PLEAS HELP

### ISSUE THREAD

**Issue by developer90210brr** [Engineer-of-Stuff/stable-diffusion-paperspace#55]
i can not get it to run on paperspace IM SO TIRED idk what the issue is but can you make a more in depth guide it does not use python 3.10.6 that is recommended on the latest version. maybe a video?

**Comment by Cyberes** [comment]
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md
https://wiredcraft.com/blog/how-we-write-our-github-issues/

I have no idea what you want.
