### ISSUE TITLE
ModuleNotFoundError: No module named 'launch'

### ISSUE THREAD

**Issue by diondwitama24** [Engineer-of-Stuff/stable-diffusion-paperspace#57]
I just did the stable-diffusion-paperspace update since a few months of not using it by creating a new notebook

But after I try to install I get this kind of error

![Screenshot (11955)](https://user-images.githubusercontent.com/123540233/214514131-0fc40c57-6d69-43a3-809e-bd56e70100a3.png)

I don't know what the cause is

**Comment by Cyberes** [comment]
The paths in the options block have changed since you last ran it. Where did you have the WebUI repo located last time you ran it?

**Comment by bachagabriel** [comment]
add the following two lines before import launch

`import os
os.chdir(repo_storage_dir+'/stable-diffusion-webui')`

**Comment by Cyberes** [comment]
Ah, I'll have to fix that.

**Comment by H1ghSyst3m** [comment]
I have the same problem, but it's my first installation. So there are no file only some

![Screenshot 2023-01-26 232938](https://user-images.githubusercontent.com/60105043/214965473-faa70712-7ae3-4d4c-8447-7e68bc4bbd1b.png)
![Screenshot 2023-01-26 233011](https://user-images.githubusercontent.com/60105043/214965479-a26a4c0c-e366-4a02-a587-83fd41cbcc2c.png)

**Comment by H1ghSyst3m** [comment]
> Ah, I'll have to fix that.

Can you also help me?

**Comment by Cyberes** [comment]
Everything should be fixed in abca842b30a4317462ca605ae90b709af93baa33. Please update your notebook.

@H1ghSyst3m can you try this new update?

**Comment by H1ghSyst3m** [comment]
thx, but it didn't work

![Screenshot 2023-01-27 084925](https://user-images.githubusercontent.com/60105043/215035387-56ff50e3-e24e-4bd3-91b5-ec275183a77b.png)
![Screenshot 2023-01-27 084957](https://user-images.githubusercontent.com/60105043/215035393-485d06c6-2aef-4253-ae56-d73f84ce9761.png)

**Comment by H1ghSyst3m** [comment]
It depends on flowdas-meta, but I can't Install flowdas-meta, I think it's not compatible with python 3.9

**Comment by H1ghSyst3m** [comment]
Do I need to change python version?
How do I do that in paperspace?

**Comment by latentwiki** [comment]
I moved the notebook into the stable-diffusion-webui directory, where it's next to launch.py, and that resolved it.

**Comment by H1ghSyst3m** [comment]
> I moved the notebook into the stable-diffusion-webui directory, where it's next to launch.py, and that resolved it.

So how I understand it is. You downloaded launch.py and uploaded it. And placed them next to each other?

**Comment by H1ghSyst3m** [comment]
Alright I found the problem.

The 'Clone the WebUi repository' block doesn't work on my notebook.

It says
stable diffusion is already downloaded, updating...

**Comment by H1ghSyst3m** [comment]
@Cyberes 
@latentwiki 
It worked after I installed the repository manually.

But now I can't launch the WebUI.
![2023-01-27 15_46_20-StableDiffus… - JupyterLab – Mozilla Firefox](https://user-images.githubusercontent.com/60105043/215114587-9e287bca-b196-4997-894b-e4e7db02392b.jpg)

**Comment by Cyberes** [comment]
I adjusted the check for the existing repo. Please try that.

> It depends on flowdas-meta, but I can't Install flowdas-meta, I think it's not compatible with python 3.9

I think you're trying to install requirements for an extension. I'd open an issue with the extension developer.
