### ISSUE TITLE
Model downloader change file name to random alphabet if I download models from huggingface

### ISSUE THREAD

**Issue by qnzkzpwldns** [Engineer-of-Stuff/stable-diffusion-paperspace#58]
![화면 캡처 2023-01-25 203105](https://user-images.githubusercontent.com/123554178/214552564-22cf3522-ee19-4d3d-9b8c-f72a5644fe83.png)
![화면 캡처 2023-01-25 203006](https://user-images.githubusercontent.com/123554178/214552580-ce8ee722-5219-426a-8980-3dbffdb0401c.png)

If I download models from huggingface it changes filename to random alphabet all of sudden.

This was working last week. 

Do you have any idea regarding this problem?

**Comment by Cyberes** [comment]
I'll need the url you're trying to download.

**Comment by qnzkzpwldns** [comment]
I think all the huggingface download urls having problem

here are some urls I was trying to download

https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0/resolve/main/dreamlike-photoreal-2.0.safetensors

https://huggingface.co/andite/anything-v4.0/resolve/main/anything-v4.5.safetensors

https://huggingface.co/nuigurumi/basil_mix/resolve/main/Basil_mix_fixed.safetensors

**Comment by Cyberes** [comment]
Aria2 uses the filename header from the download HTTP request so Huggingface must be sending something weird. The downloader will now manually set the filename using the URL string. Fixed in abca842b30a4317462ca605ae90b709af93baa33.

**Comment by qnzkzpwldns** [comment]
thanks!
