### ISSUE TITLE
RuntimeError: Couldn't clone Taming Transformers.

### ISSUE THREAD

**Issue by bachagabriel** [Engineer-of-Stuff/stable-diffusion-paperspace#59]
I just updated the notebook and saw that the file structure has now changed. As things are now being saved in /storage/ this is basically a clean install. Can't seem to get over the following error when installing requirements

`Cloning Taming Transformers into repositories/taming-transformers...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [8], in <cell line: 26>()
     24 # Import launch.py which will automatically run the install script but not launch the WebUI.
     25 import launch
---> 26 launch.prepare_environment()
     28 # Install things for this notebook
     29 get_ipython().system('pip install requests gdown bs4 markdownify')

File /storage/stable-diffusion/stable-diffusion-webui/launch.py:265, in prepare_environment()
    262 os.makedirs(dir_repos, exist_ok=True)
    264 git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
--> 265 git_clone(taming_transformers_repo, repo_dir('taming-transformers'), "Taming Transformers", taming_transformers_commit_hash)
    266 git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
    267 git_clone(codeformer_repo, repo_dir('CodeFormer'), "CodeFormer", codeformer_commit_hash)

File /storage/stable-diffusion/stable-diffusion-webui/launch.py:128, in git_clone(url, dir, name, commithash)
    125     run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
    126     return
--> 128 run(f'"{git}" clone "{url}" "{dir}"', f"Cloning {name} into {dir}...", f"Couldn't clone {name}")
    130 if commithash is not None:
    131     run(f'"{git}" -C "{dir}" checkout {commithash}', None, "Couldn't checkout {name}'s hash: {commithash}")

File /storage/stable-diffusion/stable-diffusion-webui/launch.py:74, in run(command, desc, errdesc, custom_env, live)
     66     if result.returncode != 0:
     68         message = f"""{errdesc or 'Error running command'}.
     69 Command: {command}
     70 Error code: {result.returncode}
     71 stdout: {result.stdout.decode(encoding="utf8", errors="ignore") if len(result.stdout)>0 else '<empty>'}
     72 stderr: {result.stderr.decode(encoding="utf8", errors="ignore") if len(result.stderr)>0 else '<empty>'}
     73 """
---> 74         raise RuntimeError(message)
     76     return result.stdout.decode(encoding="utf8", errors="ignore")

RuntimeError: Couldn't clone Taming Transformers.
Command: "git" clone "https://github.com/CompVis/taming-transformers.git" "repositories/taming-transformers"
Error code: 128
stdout: <empty>
stderr: Cloning into 'repositories/taming-transformers'...
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed`

**Comment by bachagabriel** [comment]
Update: I tried again it now works. I changed the repo directory from 
/storage/stable-diffusion
to 
/storage

**Comment by Cyberes** [comment]
You probably had the repo stored in `/storage/stable-diffusion-webui`. Glad you got it figured out.
