### ISSUE TITLE
xformer in free-tier

### ISSUE THREAD

**Issue by ShadeRedeye** [Engineer-of-Stuff/stable-diffusion-paperspace#60]
i just curious can  i use xformer in free tier already? is xformer can be build in /tmp/ file using sysmlink method since whenever i build it it gave size >5 gb space

**Comment by Cyberes** [comment]
I'm rewriting the xformers builder to bring it up-to-date with the WebUI's implementation. I'll push a new commit soon.

**Comment by Cyberes** [comment]
See abca842b30a4317462ca605ae90b709af93baa33
