### ISSUE TITLE
WebUI start error

### ISSUE THREAD

**Issue by TimyIsCool** [Engineer-of-Stuff/stable-diffusion-paperspace#62]
Hey so I try running the webUI but i get this error when i try run it and I have tried 3 different times to run it, any help would be amazing

/usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
[libprotobuf FATAL google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.6).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.6).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)

**Comment by Cyberes** [comment]
Uninstall protobuf then re-run the installer:
```bash
pip uninstall -y protobuf
```

**Comment by TimyIsCool** [comment]
thank you so much, last question, will this work in google colab?

**Comment by latentwiki** [comment]
> thank you so much, last question, will this work in google colab?

There's a lot of options for Colab, try https://github.com/TheLastBen/fast-stable-diffusion
