### ISSUE TITLE
Any reason why the UI doesn't update in real time as it does in collab?

### ISSUE THREAD

**Issue by bachagabriel** [Engineer-of-Stuff/stable-diffusion-paperspace#65]
Any reason why the UI doesn't update in real time as it does in collab? With a lot of extensions I find myself needing to reload gradio sometimes

**Comment by Cyberes** [comment]
What are you running in Colab?

**Comment by bachagabriel** [comment]
In Collab, TheLastBen’s auto1111 acts differently. You can see progress bars, interrupt etc…

**Comment by Cyberes** [comment]
Did you update the notebook? I removed the `--gradio-debug` arg since an update to the WebUI changes it's behavior and breaks progress bars.

**Comment by bachagabriel** [comment]
🙏🏻
