### ISSUE TITLE
Unable to use xformers | No such operator xformers_flash::flash_fwd

### ISSUE THREAD

**Issue by trigun117** [Engineer-of-Stuff/stable-diffusion-paperspace#68]
The error message is ``RuntimeError: No such operator xformers_flash::flash_fwd - did you forget to build xformers with `python setup.py develop`?`` facing it when trying to generate an image. I also tried to build and install xformers using the cells in the `Build and Install Xformers` part, but I had no luck as well.

**Hardware**: Paperspace Free A4000
**stable-diffusion-paperspace repo commit** = ae57c5b137c71f8e179f1ed55bf3643e21ea1b58
**stable-diffusion-webui repo commit** = 2c1bb46c7ad5b4536f6587d327a03f0ff7811c5d

**Comment by Cyberes** [comment]
Xformers was compiled without a few features to make the binary smaller and compile time shorter. I have an update to the notebook with instructions on how to build full xformers.

I also built xformers full last night:

```
pip install https://raw.githubusercontent.com/Cyberes/xformers-compiled/main/a4000/full/xformers-0.0.16%2B6f3c20f.d20230130-cp39-cp39-linux_x86_64.whl
```

**Comment by trigun117** [comment]
@Cyberes just tried to generate an image using **text2image** and got this error

**Comment by trigun117** [comment]
by the way installing xformers full via 
`pip install https://raw.githubusercontent.com/Cyberes/xformers-compiled/main/a4000/full/xformers-0.0.16%2B6f3c20f.d20230130-cp39-cp39-linux_x86_64.whl` fixed the issue

**Comment by Cyberes** [comment]
Cool, glad that worked. I guess I should stick with xformers full.
