### ISSUE TITLE
Installation is not persistent on paid account

### ISSUE THREAD

**Issue by GeorgeVlachakisUni** [Engineer-of-Stuff/stable-diffusion-paperspace#69]
Hello, I am facing an issue where I always have to run the first block about where to store files, and then the "Install requirements and download repositories" block after I restart the machine. I am using a paid account, and those are my storage settings:

```

# Paid Tier
model_storage_dir = '/storage/models'



# Optional path settings
repo_storage_dir = '/storage/stable-diffusion'         # Where to store your Stable Diffusion-related files.

export_storage_dir = '/notebooks/exports'              # Where the generated images will be exported to.

pip_cache_dir = '/storage/pip/cache'                   # The installer can cache pip wheels so you don't have to re-download them
                                                                             # every time you start the machine. I recommed setting it to '/storage/pip/cache'

```

Probably a user error, but I am scratching my head trying to figure this out.

**Comment by Cyberes** [comment]
The machine the notebook runs on is not persistent, meaning you always have to re-install the dependencies and such. But what is persistent are the files in `/storage/` and `/notebooks/`. That's why the `pip_cache_dir` exists, to cache the wheels and make the installation slightly faster.
