### ISSUE TITLE
Gardio times out if generation request takes too long

### ISSUE THREAD

**Issue by KLL505** [Engineer-of-Stuff/stable-diffusion-paperspace#70]
For some reason, Gardio seems to time out if the generation request takes too long and it returns with this error causing the page to no longer work after generating. The public URL still works if I open it again in another tab.  No error is recorded to the terminal but the web terminal returns with a 503 error. 
![image](https://user-images.githubusercontent.com/94243270/216457265-69c15ded-ac30-450e-8c3b-03fc5fe02317.png)  
Any idea on how to extend this timeout time to prevent this from happening?

**Comment by Cyberes** [comment]
https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/master/docs/Tunneling%20Proxy%20for%20Paperspace.md
