### ISSUE TITLE
gradio interface crashes often

### ISSUE THREAD

**Issue by Lesteriax** [Engineer-of-Stuff/stable-diffusion-paperspace#74]
in img2img tab, after generating. Quite often now it keeps crashing.

**Comment by Cyberes** [comment]
I'd check with the WebUI team first.

**Comment by CaptainGodual** [comment]
is there any update on this @Cyberes? I know I only posted a 2 days ago, just thought I'd follow up.

**Comment by Cyberes** [comment]
I'll look into adding python3.10 to the install process.

**Comment by Cyberes** [comment]
Python3.10 instructions added in https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/commit/babae8583818d8ab1234f5dd6dca8a50f49d5acd
