### ISSUE TITLE
HTTP Gradio.live link not showing up

### ISSUE THREAD

**Issue by m17reardon** [Engineer-of-Stuff/stable-diffusion-paperspace#77]
Been having issues connecting to Gradio.live for about 6 hours now. Upgraded to new notebook and now I only have the option to run the webui locally. Anybody else experiencing any issues?

**Comment by Cyberes** [comment]
Can you try adding `--share` to the line starting with `!python webui.py` in the `Launch the WebUI` block? I haven't change anything and it should show the link by default. You could also be running into issues with the Gradio servers.

**Comment by m17reardon** [comment]
It was fixed the next morning.. thank you

**Comment by m17reardon** [comment]
It was fixed the next morning
