### ISSUE TITLE
Can't delete stable-diffusion-webui folder

### ISSUE THREAD

**Issue by personxyz** [Engineer-of-Stuff/stable-diffusion-paperspace#80]
Hi,

I'm having trouble with img2img and in-painting not working (txt2img works fine) so I want to do a fresh install of everything. I updated the notebook and attempted to delete the stable-diffusion-webui folder so it could be re-installed but a message popped up saying:

Delete Failed

Directory /notebooks/storage/stable-diffusion/stable-diffusion-webui not empty.

I'm not very tech savvy so please explain where I'm going wrong as if you're talking to a five year old :) 

Thanks

**Comment by Cyberes** [comment]
`rm -rf /notebooks/storage/stable-diffusion/stable-diffusion-webui`

**Comment by personxyz** [comment]
Thanks for the very fast response. I've attached a screenshot that highlights where I'm guessing this needs to be entered. Can you clarify I'm right please, I'd hate to do this wrong and break everything.
![screenshot](https://user-images.githubusercontent.com/122485148/223521374-ef19a677-18f9-43e2-9fe3-b5241d7383c1.png)

**Comment by personxyz** [comment]
Nevermind, I figured it out and it worked. Thanks :)
