### ISSUE TITLE
Img2img/inpaint don't work at all

### ISSUE THREAD

**Issue by personxyz** [Engineer-of-Stuff/stable-diffusion-paperspace#81]
Hi,

Currently img2img and inpaint have completely stopped working for me (txt2img works fine). I tried reinstalling stable diffusion but that didn't work. 

From my research it looks like it could be a python issue. I saw that you mentioned something about this here.

I'll look into adding python3.10 to the install process.

_Originally posted by @Cyberes in https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/issues/74#issuecomment-1445182176_

I'm not trying to rush you regarding this, I'm just wondering if there's any way I can update to python 3.10 myself. I use SD to make commissions and not being able to use inpaint has completely halted my work. 

Hence I'm desperate to find a fix and will happily update python myself. That would be simple enough if everything was installed on my PC but with this being a notebook I don't really know what I'm supposed to do.

Any help would be greatly appreciated.

**Comment by Cyberes** [comment]
Oh, sorry. I had it pretty low on my priorities since I couldn't reproduce it. I'll get it done.

**Comment by personxyz** [comment]
Thanks dude, I really appreciate that, it's been a super-stressful week because of this issue. Your notebook + paperspace have been a dream come true for someone like me who doesn't have a powerful PC for running Stable Diffusion.

Thanks for all the hard work!

**Comment by ohgodaaaa** [comment]
It works well for me.
Could you describe the situation detailedly?

**Comment by Cyberes** [comment]
@personxyz I built a custom container. Follow this guide and enter `cyberes/gradient-base-py3.10` for your container name.

https://docs.paperspace.com/gradient/notebooks/runtimes/#how-to-specify-a-custom-container

**Comment by personxyz** [comment]
Hi @Cyberes,

Thanks for working so fast to fix this. Sadly I couldn't get it working. I deleted my old notebook, created a new one and entered cyberes/gradient-base-py3.10 as the container name. However, once I tried to run the new notebook an error message appeared and it wouldn't start. 

![Error Message](https://user-images.githubusercontent.com/122485148/224501982-18cb311f-946b-4791-ab8b-42567ae055db.png)

I've tried several times but this same error message keeps appearing.

**Comment by Cyberes** [comment]
Ok maybe it wants `cyberes/gradient-base-py3.10:latest`

**Comment by personxyz** [comment]
It worked!

Even better, the Python update seems to have resolved the img2img/inpaint issues. I only tested both for a few minutes but they were working perfectly. Thanks for the excellent work Cyberes.

One minor problem did arise, I got the following error message when I was running the notebook cells:

![xformers error](https://user-images.githubusercontent.com/122485148/224510319-71c8672a-c2fa-453b-a281-781661591a0c.png)

So sadly xformers wasn't installed, don't know what happened there but it's a small problem compared to the img2img/inpaint one at least.

**Comment by Cyberes** [comment]
Oh yeah its a different platform with that new container. You can use the tool at the bottom to build xformers yourself.

**Comment by personxyz** [comment]
Sadly within 15 minutes of using Stable Diffusion today the problem arose again. It seems to only be a problem for people running SD through notebooks. I've seen multiple colab users also report this issue but the wider SD community (people using it through their own PC's) don't seem to have a problem. There's no mention of it on the biggest discord servers/subreddits and I imagine if inpainting/img2img had broken for everyone it would be huge news by now.

I wonder if one of the many auto1111 updates fundamentally broke something regarding notebooks and SD. The problem first arose for me on the 5th of March so I'm going to try an earlier commit and see what happens. I'll report back.

**Comment by personxyz** [comment]
OK, I tried going back to an older auto1111 commit from the 2nd of March and that seems to have fixed the issue, I've just spent the last 90 minutes inpainting with absolutely no problems. For anyone who wants to try this, the commit I used was: fc3063d9b924c094b59229269f4afe722b120d88

It's obviously not a perfect solution but until the root cause is figured out this is likely the best option.

**Comment by Cyberes** [comment]
Could you [file an issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues) on the WebUI? I've also alerted the team of this issue so make sure to link this issue to the one on the WebUI repo.

**Comment by personxyz** [comment]
I created a bug report for the WebUI a few days ago but there hasn't been any response apart from other users saying they're suffering the same problem. I've now edited it to link back to this issue so I guess all we can do now is wait.

**Comment by personxyz** [comment]
> OK, I tried going back to an older auto1111 commit from the 2nd of March and that seems to have fixed the issue, I've just spent the last 90 minutes inpainting with absolutely no problems. For anyone who wants to try this, the commit I used was: fc3063d9b924c094b59229269f4afe722b120d88
> 
> It's obviously not a perfect solution but until the root cause is figured out this is likely the best option.

Update: Now this older commit isn't working for me! I'm starting to go insane trying to fix this damn problem. I guess I'll try a different commit but I don't hold out much hope.

**Comment by Cyberes** [comment]
Just nuke everything and reinstall. Make sure to delete everything in `/storage` too.

**Comment by personxyz** [comment]
> Just nuke everything and reinstall. Make sure to delete everything in `/storage` too.

I'll try that tomorrow I guess. 

Someone said "Checking "use_localtunnel" seems to solve the issue". I think that's an option in the colab notebook by TheLastBen. Can we do something similar in your notebook?

**Comment by Cyberes** [comment]
Bad idea. https://gist.github.com/Cyberes/f050b03e59ccdf232527751f17f7ae4e

**Comment by personxyz** [comment]
I think the problem was Gradio related. I reverted from 3.16.2 to 3.13.0 and that seemed to fix the issue. 

However, it also created a new one. After 10 minutes of working perfectly my images stopped displaying. I could click generate and SD would run as normal but nothing would show and I'd get this error message: OSError: Socket is closed

After further research this again seems to be a Gradio issue and so far there's only a semi-decent fix for it which involves reverting back to some auto1111 commit from December. Sadly this fix breaks inpainting which is the main reason I use SD. 

By this point I decided to look at alternatives to Gradio as it's buggy as hell. This colab notebook has added multiple alternatives as shown [here.](https://github.com/camenduru/stable-diffusion-webui-colab/issues/172)

That lead me to @Bing-su's [sd-webui-tunnels extension](https://github.com/Bing-su/sd-webui-tunnels). I installed it on my WebUI. Then I added `--cloudflared` to here in the paperspace notebook:

![Cloudfared](https://user-images.githubusercontent.com/122485148/225408507-7efe1747-41f0-4f02-a82e-065d5fa23ea6.png)

Then I updated the webui-user.bat file by adding `--cloudflared` to COMMANDLINE_ARGS. 

I won't celebrate too early as there's been some false dawns before but inpainting is working and my generated images now show. I'm cautiously optimistic but I guess we'll see over the coming days what happens. 

@Cyberes, maybe you could do something similar to the colab notebook I linked up above so that there's some Gradio alternatives.

**Comment by Cyberes** [comment]
I had a client get banned from Paperspace for using Cloudflare Tunnel.

**Comment by personxyz** [comment]
> I had a client get banned from Paperspace for using Cloudflare Tunnel. Be careful.

Damn, whenever I think this problem is finally over something new pops up. What about the others options in the [sd-webui-tunnels extension](https://github.com/Bing-su/sd-webui-tunnels), localhost.run and remote.moe? Are they OK?

If not then what options are Paperspace cool with, surely there must be some.

**Comment by Cyberes** [comment]
They likely have a big list of proxy services. Just run your own and avoid the whole problem. https://gist.github.com/Cyberes/f050b03e59ccdf232527751f17f7ae4e

**Comment by personxyz** [comment]
I've had a talk with someone from paperspace support. I was going to use cloudflare as a tunnel but was told by paperspace not to (you did warn me so thanks for that lol).

Fortunately I have been allowed to briefly test whether ngrock works to prove whether gradio is the source of my problems. I thought ngrock would be easy to install seeing as it's already integrated with the WebUI but I'm having some issues. 

I added --ngrok {myauthtoken} --ngrok-region eu to COMMANDLINE_ARGS in the wubui-user.bat file. That didn't actually do anything though when I ran the notebook, only the standard gradio links showed up.

I know I'm likely missing some obvious step so any guidance would be greatly appreciated. 

Do I have to pip install ngrock? Is there something I need to add to the "Launch the WebUI" cell block?

Thanks

**Comment by personxyz** [comment]
Nevermind, I installed pyngrock and added the commandline args to the "Launch the WebUI" cell block and that worked. The speed difference is huge. It's roughly twice as fast in comparison to Gradio at its best. Inpainting is working fine. If it stays that way for all of tomorrow I think I can finally conclude that Gradio was the root cause. 

Seeing as I can't use ngrock long-term I'll have a look at that rathole server guide you wrote, thanks for all the help @Cyberes!

**Comment by personxyz** [comment]
I think this can be closed now. Everything is working great now I've switched from Gradio. @Cyberes, your rathole server guide was very helpful! Thanks for everything.

**Comment by Cyberes** [comment]
Awesome! Glad it worked out.
