### ISSUE TITLE
gradio link stopped working after installing xformers

### ISSUE THREAD

**Issue by Lesteriax** [Engineer-of-Stuff/stable-diffusion-paperspace#83]
Seeing I was having issues with img2img tab, I used the container provided and everything was working fine. However, xformers needed to be installed so I ran the two blocks, the second one took about 15 minutes to finish. 

When that was done, I could not load gradio at all. Getting 504 Gateway Time-out not sure if went wrong here

**Comment by m17reardon** [comment]
I updated to new container this morning with Python 3.10 and I am getting 504 Gateway Time-out as well.

**Comment by m17reardon** [comment]
Must be a gradio issue. Isn't working on colab either

**Comment by m17reardon** [comment]
![image](https://user-images.githubusercontent.com/12926842/224707602-6a03b11b-bfca-4c30-9037-42fbb1f154db.png)

**Comment by RabblerouserGT** [comment]
That's just people reporting outages. Could still be out but considering it's just 27 reports, don't rule other potential links in the chain being broken.

I know I'm having issues with xformers myself, getting `ERROR: xformers-0.0.14.dev0-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.` in the "Install requirements" section.

**Comment by Cyberes** [comment]
If you use the Py3 container you will have to rebuild xformers using the block in the Tools section. Should be pretty easy and only needs to be done once.

**Comment by Lesteriax** [comment]
> If you use the Py3 container you will have to rebuild xformers using the block in the Tools section. Should be pretty easy and only needs to be done once.
> 
> As for the Gradio issue, I gave up on them. Between the slow speeds and critical bugs it's just a mess. I run a similar service for myself that uses rathole [which I wrote a guide to set up for yourself](https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace/blob/7b17e4965ad72f73dbf06b72b0158f94d8c48e68/docs/Tunneling%20Proxy%20for%20Paperspace.md).

After several hours of trails and errors, and with the help of chatgpt, I reached the area where I need to install rathole on the client. I tried on paperspace using terminal but the whenever I want to run the config.toml, it says bash command not found...Tried several times to install rathole as instructed on the guide using paperspaces' terminal but it just won't work. Could you point me to what I should do?

I feel like your guide should also be dumbed down to idiots like me or new comers with little knowledge.

PS. Today I learned the following commands: ls, tree -d, cd .., nano (loved this :D)

**Comment by Lesteriax** [comment]
> 

Thanks a lot, I finally got it to work!

Loving the speed, I can even have the live generation views with no issues! :D
