### ISSUE TITLE
X-Formers install causing issues

### ISSUE THREAD

**Issue by m17reardon** [Engineer-of-Stuff/stable-diffusion-paperspace#88]
Whenever I install xformers it gives me errors when I try to create an image in automatic1111. When I rerun the install block as suggested it gives me a ton of errors and won't even launch the webui. Is anyone else having issues? I miss being able to have xformers working. Only fix is to shutdown the machine and start over.

**Comment by Cyberes** [comment]
Ok well I'll need some logs.
