### ISSUE TITLE
Web UI Start Problem

### ISSUE THREAD

**Issue by kuhsturm** [Engineer-of-Stuff/stable-diffusion-paperspace#89]
/storage/stable-diffusion/stable-diffusion-webui
/usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
  
  I am getting this error when trying to start web ui
  
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1+cu117 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 4.22.1 which is incompatible.

**Comment by kuhsturm** [comment]
i am install torch 1.13.1 and protobuf 3.20.0 and fixed but getting this error now.

/storage/stable-diffusion/stable-diffusion-webui
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu117 with CUDA 1106 (you have 1.13.1+cu117)

**Comment by Cyberes** [comment]
Rebuild xformers using the block in the tools section.
