### ISSUE TITLE
XFormers install problem on A4000

### ISSUE THREAD

**Issue by johnsonjsyuen** [Engineer-of-Stuff/stable-diffusion-paperspace#91]
First off, thank you so much for your work. It's very convenient and well thought out.

I started on a A4000 using the docker image `cyberes/gradient-base-py3.10:latest`.

In the cell `Install requirements and download repositories)` unfortunately got 

```
2023-04-11 21:17:30 (190 MB/s) - ‘/tmp/tmp.HESlGaVPwI/xformers-0.0.14.dev0-cp39-cp39-linux_x86_64.whl’ saved [14622428/14622428]

ERROR: xformers-0.0.14.dev0-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.
```

Similar problem on RTX5000

Overriding it to use `xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl` instead also did not work
Thanks

**Comment by johnsonjsyuen** [comment]
In the end installing with 

`!pip install xformers`

worked

**Comment by Cyberes** [comment]
Yup, it's time to rebuild xformers again...

Glad pip is working now.

**Comment by johnsonjsyuen** [comment]
thanks!

**Comment by fritzy3** [comment]
> In the end installing with
> 
> `!pip install xformers`
> 
> worked

I have the same issue, where and when do you write "!pip install xformers"
You add it to one of the cells, not execute it manually in the terminal every launch, right?

**Comment by adamengberg** [comment]
hi there, when running the "!pip install xformers" cell in seems to install correctly. when running the "install dependencies" cell again as specified, the new xformers is uninstalled so when i launch the webui it does not use xformers. 

If i skip running the "install dependencies" cell after "!pip install xformers", the webui does use xformers, but there is no change in speed. Do you have any idea on how to resolve this?

**Comment by johnsonjsyuen** [comment]
@fritzy3 I put a call to `!pip install xformers` right after the install dependencies cell in it's own cell. I use the `cyberes/gradient-base-py3.10:latest` base docker image.

@adamengberg  I used an A4000 and I believe it's a bit faster? I haven't comprehensively benchmarked it so it may well be no faster.

**Comment by Cyberes** [comment]
I'm not supporting `!pip install xformers` because (during my testing) doing it that way installs pyTorch 2.0 which isn't the version the WebUI wants. See https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/launch.py#L228

If it works for you guys, great.
