### ISSUE TITLE
Add lora downloader to /tmp directory 

### ISSUE THREAD

**Issue by hoangpq14736** [Engineer-of-Stuff/stable-diffusion-paperspace#93]
Hello, this is not an issue. Just asking if you can add a block to download lora file to the Lora folder in /tmp directory please? I have spent last 3 hours to find a way to modify the model downloader block just to download lora since every link I pasted in that block will be download to the model_storage_dir and can not be detected by the webui.

**Comment by Cyberes** [comment]
You need to re-link the models back to the webui using the link block
