### ISSUE TITLE
Support for vladmandic/automatic fork?

### ISSUE THREAD

**Issue by fritzy3** [Engineer-of-Stuff/stable-diffusion-paperspace#94]
Thank you for making this paperspace notebook, I use it daily for my professional work!

It seems there's a better version of Auto1111 emerging, better UI, better maintenance, new features, etc...
https://github.com/vladmandic/automatic?fbclid=IwAR0Fbmgbcvq8sWFfUQBpsCVYTwA5o4nAbAcUp3NjIII2ymSuBicmoZyQOd8

would be amazing if we could use that on paperspace too. maybe it's possible to add it to this notebook and have an option which fork to launch?

thanks anyway.

**Comment by Cyberes** [comment]
I welcome pull requests.
